navikt/syfooversiktsrv

- src/main/kotlin/no/nav/syfo/Environment.kt
- src/main/kotlin/no/nav/syfo/SyfooversiktApplication.kt
- src/main/kotlin/no/nav/syfo/kafka/Kafka.kt
- src/main/kotlin/no/nav/syfo/metric/Metrics.kt
- src/main/kotlin/no/nav/syfo/oversikthendelsetilfelle/OversikthendelstilfelleService.kt
- src/main/kotlin/no/nav/syfo/oversikthendelsetilfelle/domain/KOversikthendelsetilfelle.kt
- src/main/kotlin/no/nav/syfo/personstatus/OversiktHendelseService.kt
- src/main/resources/localEnvForTests.json
- src/test/kotlin/no/nav/syfo/KafkaITSpek.kt
Dette er første del av mottatt av oppfolgingstilfelle som oversikthendelse i syfooversikt.
Denne delen inkluderer kun mottak og tellere av ulike varianter av hendelsene, uten noe endringer i database.
> Receive event oversikthendelsetilfelle

- src/main/kotlin/no/nav/syfo/personstatus/PersonOversiktStatusAksesseringQueries.kt
- src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt
- src/test/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusApiSpek.kt
All persons with oppfolgingsplanLPSBistandUbehandlet=true should be returned in hentPersonoversiktStatusTilknyttetEnhet even though no Oppfolgingstilfelle exists on the PersonOversiktStatus. OppfolgingsplanLPSBistand that are Ubehandle should be shown to a Veileder of a Enhet because it is not a requirement for a person to be sick, to have been sick or to have received Sykepenger.
> Return PersonOversiktStatus with oppfolgingsplanLPSBistandUbehand=true

- src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
Da enkelte rådgivere ikke får syfooversikt opp i det hele, tenker jeg vi øker timeout til 30 sek med en gang (default er 15) - og forsøker å nøste opp i ytelseproblemene i egen oppgave.
> Øker timeout som midlertidig fiks

- src/main/resources/db/migration/V11_4__add_columns_tilfelle_and_create_table_tilfelle_virksomhet.sql
Add columns in PERSON_OVERSKT_STATUS to store relevant information about the latest Oppfolgingstilfelle of a Person.
The latest Oppfolgingstilfelle will be consmed  from topic isoppfolgingstilfelle-oppfolgingstilfelle-person. Also create table PERSON_OPPFOLGINGSTILFELLE_VIRKSOMHET to store a list of Virksomhet from latest Oppfolgingstilfelle of  a Person. Virksomhet has a non-null Virksomhetsnummer from the latest Oppfolgingstilfelle and a nullable Virksomhetsnavn that will be retrieved from Ereg where needed.
>  Create table and add columns for latest Oppfolgingstilfelle

- src/test/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/cronjob/virksomhetsnavn/PersonOppfolgingstilfelleVirksomhetsnavnCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/personstatus/KafkaOppfolgingstilfellePersonServiceSpek.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt
A singleton instance of InternalMockEnvironment containing internal classes used in tests, is created and used in all tests to avoid repetitive initialization.
> Create resuable InternalMockEnvironment for tests

- src/main/resources/db/migration/V12_4__add_index_enhetens_oversikt.sql
Ser at noen tilfeller i produksjon fortsatt tar 10-20 sekunder, selv om snittet er 2-3 sekunder. Tror en slik partiell indeks vil forbedre det betydelig.
> Add specific index for enhetens oversikt

- .nais/naiserator-prod.yaml
Kan like godt enable disse nå: 
1. Prosessering av møtestatus er ok (vil lage nye forekomster/oppdatere eksisterende med siste dialogmøtestatus)
2. Kandidat-topic'en er tom - vil bli populert når cronjob'en i isdialogmotekandidat skrus på mandag 19. sept,
> Enable toggles in prod

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
- src/test/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/personstatus/KafkaOppfolgingstilfellePersonServiceSpek.kt
- src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt
- src/test/kotlin/no/nav/syfo/testutil/generator/KafkaOppfolgingstilfellePersonGenerator.kt
Dette relaterer seg til en jira-sak der oppfølgingstilfellet i syfoversikt fikk lengde 1 uke, mens arbeidstakeren hadde vært sykmeldt mye lengre.
Dette kunne skje når to påfølgende oppdateringer fra Kafka hadde samme inntruffet-tidsstempel.
> Bugfix: oppdater oppfolgingstilfelle ved lik inntruffet-timestamp

- src/main/resources/db/migration/V12_6__add_aktivitetskrav.sql
`aktivitetskrav` is the status - "NY", "OPPFYLT", etc.
`stoppunkt` is the day the innbygger passes 8 weeks syketilfelle.
`updated_at` is the time of the last change on aktivitetskrav.
> Add columns for aktivitetskrav

- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
- src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt
- src/test/kotlin/no/nav/syfo/testutil/TestApiModule.kt
I stedet for å initialisere disse rundt omkring i appen, så flyttes det til å initialiseres i App. Det _kan_ være noe state knyttet til Redisstore som det er greit å beholde.
> Initialize redis and azureClient in App

- src/main/kotlin/no/nav/syfo/identhendelse/IdenthendelseService.kt
- src/main/kotlin/no/nav/syfo/identhendelse/database/IdenthendelseQuery.kt
- src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt
I de tilfellene vi har den nye aktive identen allerede i databasen ved gjennomlesning av topic, får vi en feil på fnr-constraint. Løsningen er å heller slette gammel rad enn å overskrive fnr for den raden. Samtidig ønsker vi å kopiere over verdi for tildelt veileder fra gammel til ny rad dersom den mangler for den nye identen.
> Update or override and delete from identhendelse

- src/main/kotlin/no/nav/syfo/pdlpersonhendelse/PdlPersonhendelseService.kt
Så i dev at veldig mange havnet i catch-blokka, og det er kanskje å anta at dette er mer normal oppførsel enn først antatt. Kan derfor endre logging fra error til warning, og så ta en dobbeltsjekk på at ikke innholdet i lista er null. Dette er Java-klasser så litt vanskelig å vite når vi får platform-typer.
I tillegg så virker det som at det kommer mye aktørIDer her (som er 13 siffer langt), så filterer ut de også.
> Handle different types of personidenter from kafkatopic

- src/main/kotlin/no/nav/syfo/util/StringUtil.kt
Hvis du har JAN OLA som fornavn fra PDL, ble det bare Jan ola med gammel logikk. Dette håndterer fortsatt ikke vanskelige caser som McCarty og lignende navn.
Blir brukt her:
> Capitalize all names

- src/main/resources/db/migration/V13_3__repair_motebehov.sql
Var litt for raske med forrige PR: siden esyfo merget sine tilpasninger først ble det noen minutter der vi tok i mot MOTEBEHOV_SVAR_MOTTATT og MOTEBEHOV_SVAR_BEHANDLET fra ny topic uten å behandle dem riktig (siden tilpasningene for å gjøre det lå i vår pull request som ble merget etterpå). Burde delt våre tilpasninger i to PR'er.
Vi har funnet igjen de Kafka-record'ene som ble lest uten at noe ble oppdatert i databasen, og laget et db-script som setter motebehov_ubehandlet til false for forekomstene av MOTEBEHOV_SVAR_BEHANDLET og til true for forekomstene av MOTEBEHOV_SVAR_MOTTATT.
> Compensate for skipped Kafka-records

- src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
Dette reverter i praksis #213
Vi fant ut at det er best om oppgaven består, og så får veileder vurdere selv om tilfellet egentlig er utdatert (da må det også gjøres en endring i syfomodiaperson).
Hvis en innbygger kommer så langt at de skal vurderes for aktivitetskrav, setter vi det gamle til automatisk_oppfylt e.l.
> Return aktivitetskrav even if it's from previous tilfelle

- src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/kafka/KafkaAktivitetskravVurderingTask.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonTask.kt
Vi får mange db-konflikter nå og antar at det skyldes at oppfølgingstilfelle og aktivitetskrav for samme person leses samtidig fra Kafka. Ved å redusere poll-størrelse vil vi commit'e oftere og redusere sannsynligheten for slike konflikter.
> Reduce poll size

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/identhendelse/IdenthendelseService.kt
- src/main/kotlin/no/nav/syfo/kafka/KafkaModule.kt
- src/main/kotlin/no/nav/syfo/personstatus/db/getFromPersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/domain/PPersonOversiktStatus.kt
- src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt
- src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt
- src/test/kotlin/no/nav/syfo/testutil/generator/PPersonOversiktStatusGenerator.kt
Geir og jeg diskuterte dette, vi endte opp med å prøve følgende:
1. Dersom det feiler mot PDL nå når vi leser historiske endringer, så prøver vi å logge `uuid`en til den identen i vår database, slik at vi kan undersøke denne med pdl for å finne hva som er galt
2. Når vi er ferdig med å lese historiske endringer, bytter vi til å prosessere som før igjen
3. Dersom det ble veldig mange uuider å følge opp manuelt i loggen, må vi se på om logikken vår er feil. Det er uansett ikke krise om vi da må lese topicet på nytt, eller om vi bare fikk oppdatert deler av identene. 
Jeg har kommentert ut litt kode per nå, og mulig noen av metodenenavnene kanskje ikke gir like mye mening, men planen er altså å bytte tilbake igjen når vi har fått lest gjennom de historiske endringene og er over på å …
> Skip processing of not-updated identhendelser in PDL

- src/main/kotlin/no/nav/syfo/identhendelse/kafka/IdenthendelseConsumerService.kt
- src/main/kotlin/no/nav/syfo/kafka/KafkaTask.kt
Dette blir mer likt som i de andre appene, og _helt likt_ som i `isaktivitetskrav` der `pollAndProcessRecords`-funksjonen ikke er en suspend, men har en `runBlocking`.
> Retry via unsubscribe and delay on error in identhendelse

- src/main/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetQuery.kt
- src/main/kotlin/no/nav/syfo/cronjob/virksomhetsnavn/PersonOppfolgingstilfelleVirksomhetsnavnQuery.kt
- src/test/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/cronjob/virksomhetsnavn/PersonOppfolgingstilfelleVirksomhetsnavnCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/AktivitetskravPersonoversiktStatusApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/testutil/generator/AktivitetskravGenerator.kt
Sjekket i prod-databasen og det ser ut til å bli cirka 20k rader med aktivitetskrav som må oppdateres for hver cronjob. Tenker det bør gå greit å starte i ettermiddag f.eks.
> Include aktivitetskrav in cronjob queries

- src/main/resources/db/migration/V14_3__close_motebehov.sql
We don't know why these motebehov_ubehandlet are true. 4 of the users don't even exist in syfomotebehov. Others haven't been sick in years. Theories that have been checked out:
* Changed identities: PDL only had one id on the users we checked
* Saving in syfomotebehov failed, but the entry still ended up on Kafka: not possible
* Scripts/code that wrongfully deleted entries i syfomotebehov: nothing that have been committed
The list we're setting to false here is based on a query made across the databases of the two apps, it contains all the current erronous true ubehandlet_syfomotebehov. The plan now is to wait for new entries. It will hopefully be easier to debug the error when it happens in a more current state of the environment.
> Close open motebehov that are closed in syfomotebehov

- src/test/kotlin/no/nav/syfo/testutil/TestDatabase.kt
Denne testet funker ved deploy, men funker ikke lokalt. Teorien er at ingen har kjørt PersonBehandlendeEnhetCronjobSpek-testene lokalt siden overgang til sommertid 🤷🏼‍♂️
> Fix timezone issues in test

- build.gradle.kts
- src/main/kotlin/no/nav/syfo/application/api/authentication/ApiFeature.kt
- src/main/resources/logback.xml
Hvis hypotesen om at ChannelWriteException-feilene skyldes at klienten har navigert vekk fra siden, så kan vi likegodt sørge for at disse feilene ikke logges.
Litt usikker på om dette gjør susen, må nesten forsøkes i praksis.
> Filter out ChannelWriteException from log

- src/main/resources/db/migration/V15_0__close_oppfolgingsplan_lps.sql
The original oppfolgingsplan was deleted, so it's not possible to close this manually. Last oppgave of that type is closed in ispersonoppgave here https://github.com/navikt/ispersonoppgave/pull/146 This is needed as well because ispersonoppgave doesn't automatically send event on kafka when LPS-oppgave is closed with flyway script.
https://jira.adeo.no/browse/FAGSYSTEM-284794
> Close oppgave for oppfolgingsplanlps

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt
- src/main/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetCronjob.kt
- src/main/kotlin/no/nav/syfo/kafka/KafkaModule.kt
- src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt
- src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt
Bakgrunn: Personer som er nye i oversikten (f.eks. pga huskelapp) må få satt tildelt enhet for at de skal dukke opp i oversikten. Prøver derfor å kjøre cronjobben som setter/oppdaterer dette litt oftere. 
Ser ut til at den bruker opp mot 10 minutter på å kjøre i prod, så tenker hvert 15. minutt skal gå greit. Setter den til å kjøre enda oftere i dev.
> IS-1671: Increase behandlende enhet cronjob freq

- build.gradle.kts
Se https://github.com/navikt/syfooversiktsrv/security/dependabot/17
> Upgrade apache zookeper transitive dependency

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
- src/main/kotlin/no/nav/syfo/client/ClientEnvironment.kt
- src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt
- src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt
- src/main/kotlin/no/nav/syfo/metric/Metrics.kt
- src/test/kotlin/no/nav/syfo/cronjob/preloadcache/PreloadCacheCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/testutil/ExternalMockEnvironment.kt
- src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt
- src/test/kotlin/no/nav/syfo/testutil/mock/VeilederTilgangskontrollMock.kt
Use new API for preloading cache and filtering list of people. We need to do both at the same time, because the filtering relies on stuff being cached in the same tilgangskontroll app. Remove syfo-tilgangskontroll which is no longer in use.
> IS-1686: Use new tilgangskontroll app

- src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt
- src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt
- src/main/kotlin/no/nav/syfo/cronjob/preloadcache/PreloadCacheIstilgangskontrollCronjob.kt
Use cronjob with same logic as preloading syfo-tilgangskontroll.
Run this as well as the old cron job preloading in syfo-tilgangskontroll.
Still use syfo-tilgangskontroll for actually checking access to brukere
> Preload cache in istilgangskontroll

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/Oppfolgingstilfelle.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePerson.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
- src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt
- src/main/kotlin/no/nav/syfo/personstatus/api/v2/PersonOversiktStatusDTO.kt
- src/main/kotlin/no/nav/syfo/personstatus/db/PersonOppfolgingstilfelleVirksomhetQuery.kt
- src/main/kotlin/no/nav/syfo/personstatus/db/createOrUpdatePersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/db/getFromPersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/domain/PPersonOppfolgingstilfelleVirksomhet.kt
- src/main/kotlin/no/nav/syfo/personstatus/domain/PPersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt
- src/test/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/cronjob/virksomhetsnavn/PersonOppfolgingstilfelleVirksomhetsnavnCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/OppfolgingstilfelleSpek.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
- src/test/kotlin/no/nav/syfo/personstatus/KafkaOppfolgingstilfellePersonServiceSpek.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/testutil/assertion/PPersonOversiktStatusAssertion.kt
- src/test/kotlin/no/nav/syfo/testutil/assertion/PersonOversiktStatusDTOAssertion.kt
- src/test/kotlin/no/nav/syfo/testutil/generator/KafkaOppfolgingstilfellePersonGenerator.kt
- src/test/kotlin/no/nav/syfo/testutil/generator/OppfolgingstilfelleGenerator.kt
- src/test/kotlin/no/nav/syfo/testutil/generator/PPersonOversiktStatusGenerator.kt
Etter siste endringer på oppfølgingstilfelle får man nå inn `antallSykedager` på kafka. Dette vil vi lagre i databasen, og bruke til å kalkulere varigheten på sykefraværet i uker. Bruker samme utregning for varighetUker som i [denne PRen](https://github.com/navikt/isoppfolgingstilfelle/pull/165/files#diff-6e96db1980cdcec11d3dfb14b5eec8de9e0dc39b48f139d465b4fd9cf702eb36).
Har også flyttet på `Oppfolgingstilfelle`-klassen, inn i sin egen mappe. Dette fører til litt diffs i imports. 
Denne er nok lettere å lese commit for commit sånn sett.
1894 er året Coca Cola selges for første gang på flasker, og Nikita Khrusjtsjov ble født.
> IS-1894: Consume antallSykedager from oppfolgingstilfelle and calculate varighetUker in DTO

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/Oppfolgingstilfelle.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/OppfolgingstilfelleSpek.kt
Vi ser at noen oppfølgingstilfeller har negativ varighet fordi det begynner i fremtiden. Akkurat disse casene er sånn sett greie at får varighet 0, og er ikke noe som trenger å logges/undersøkes nærmere.
> IS-1894: Only log when varighet is negative and oppfolgingstilfelleStart is in the past

- src/main/resources/db/migration/V15_9__close_motebehov.sql
Manuell lukking av møtebehov som står som ubehandlet, ref Jira sak: https://jira.adeo.no/browse/FAGSYSTEM-302676
Møtebehovet er behandlet i [syfomotebehov](syfomotebehov)-databasen.
Fant ikke spor av motebehov-behandlet-hendelse på kafka-topicen for `personoppgavehendelse` (vha [iskafkamanager](https://iskafkamanager.intern.nav.no/index.html)), så mest sannsynlig noe som har gått galt ved publisering av denne...
Har ingen logger å grave i siden det er mer enn 3mnd siden møtebehov ble behandlet. Vi får undersøke mer hvis feilen oppstår igjen.
> IS-1752: Close behandlet motebehov

- src/test/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatusSpek.kt
Det kom inn en [Jira](https://jira.adeo.no/browse/FAGSYSTEM-318470)-sak hvor personen vises som dialogmøtekandidat i syfomodiaperson, men uten dialogmøtekandidat-hendelse i oversikten. Årsaken er at vi venter en uke med å vise personen som dialogmøtekandidat i oversikten for å gi partene mulighet til å besvare møtebehov først. La til en test for å dokumentere dette bedre.
Tenkte også å lage en PR på Api-et i isdialogmøtekandidat slik at personen ikke dukker opp for tidlig som kandidat i syfomodiaperson.
> IS-2086: Add test for isDialogmotekandidat logic

- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt
- src/main/kotlin/no/nav/syfo/kafka/KafkaModule.kt
- src/main/kotlin/no/nav/syfo/trengeroppfolging/TrengerOppfolgingService.kt
- src/main/kotlin/no/nav/syfo/trengeroppfolging/kafka/TrengerOppfolgingTask.kt
- src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt
- src/test/kotlin/no/nav/syfo/trengeroppfolging/kafka/TrengerOppfolgingConsumerSpek.kt
Mulig løsning på at personer ikke dukker raskt nok opp i oversikten når det lages oppfølgingsoppgave.
Når vi mottar records med oppfølgingsoppgave og har lagret/oppdatert personene i oversikten, går vi i tillegg gjennom records med aktiv oppfølgingsoppgave og gjør et forsøk på å oppdatere tildelt enhet for disse personene.
Dersom noe feiler logges dette (og personen vil bli plukket opp av den "vanlige" cronjobben som oppdatere tildelt enhet).
Tanker/innspill?
> Update behandlende enhet on received active oppfolgingsoppgave

- src/main/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetQuery.kt
- src/main/kotlin/no/nav/syfo/cronjob/virksomhetsnavn/PersonOppfolgingstilfelleVirksomhetsnavnQuery.kt
- src/main/kotlin/no/nav/syfo/frisktilarbeid/kafka/KafkaFriskTilArbeidMetric.kt
- src/main/kotlin/no/nav/syfo/frisktilarbeid/kafka/KafkaFriskTilArbeidTask.kt
- src/main/kotlin/no/nav/syfo/personstatus/db/getFromPersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt
- src/main/resources/db/migration/V16_4__adjust_frisktilarbeid_index.sql
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
Hente ut personer til oversikten som har `friskmelding_til_arbeidsformidling_fom` satt. Datoen vil nulles ut når vedtaket ferdigbehandles i Modia.
> IS-2372: Adjust friskmelding_til_arbeidsformidling_fom sql clause

- src/main/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetQuery.kt
- src/main/kotlin/no/nav/syfo/cronjob/virksomhetsnavn/PersonOppfolgingstilfelleVirksomhetsnavnQuery.kt
- src/main/kotlin/no/nav/syfo/personstatus/db/getFromPersonOversiktStatus.kt
- src/main/resources/db/migration/V16_5__add_column_arbeidsuforhet_aktiv_vurdering.sql
- Legger til kolonne som holder styr på om det finnes en aktiv 8-4 (arbeidsuforhet) vurdering. Skal brukes til å bestemme om vi skal hente domenedata fra `isarbeidsuforhet`. 
Se trellolapp for mer info
> IS-2271: Add column to keep track of arbeidsuforhet vurdering

- src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt
Vi synes det er litt rart at man for en hel enhet først har aktive oppgaver i syfooversiktsrv, men når man spør ishuskelapp så svarer den med 204 No Content. Vi vil grave litt i de tilfellene og legger derfor på en logging.
> IS-1932: Log enhet for when huskelapp gives no content

- src/main/kotlin/no/nav/syfo/personstatus/application/arbeidsuforhet/ArbeidsuforhetvurderingDTO.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/ArbeidsuforhetvurderingRecord.kt
Litt kjedelig at det må oppdateres to steder siden den er definert både der vi har DTOen vi henter fra isarbeidsuforhet-api og for kafka-recorden. Noen som har forslag til passende sted å samle det? Eventuelt kunne vi fjernet det fra kafka-recorden siden vi ikke bruker det til noe der :man_shrugging:
> IS-2454: Add IKKE_AKTUELL arbeidsuforhet vurdering type

- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/azuread/AzureAdClient.kt
- src/test/kotlin/no/nav/syfo/personstatus/infrastructure/clients/azuread/AzureAdClientSpek.kt
- src/test/kotlin/no/nav/syfo/testutil/UserConstants.kt
- src/test/kotlin/no/nav/syfo/testutil/mock/AzureAdMock.kt
Vi cacher allerede system-token, men vil cache obo-token. Har kopiert en del fra `istilgangskontroll`. Vi lagrer cache-key på system og veileder-ident, det burde være riktig 😬
> IS-2465: Cache obo-tokens from azure

- src/main/kotlin/no/nav/syfo/personstatus/db/getFromPersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/behandlendeenhet/PersonBehandlendeEnhetQuery.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/virksomhetsnavn/PersonOppfolgingstilfelleVirksomhetsnavnQuery.kt
- src/main/resources/db/migration/V17_2__update_index_enhetens_oversikt.sql
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/AktivitetskravPersonoversiktStatusApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatusSpek.kt
Raskeste løsning på å få vist de som bare har startet ny vurdering i oversikten. 
Litt relatert til dette og oppgaven som går på å vise personen i oversikten når forhåndsvarsel er sendt så tenker jeg vi videre kan gjøre følgende:
- lage bulk-endepunkt i `isaktivitetskrav` for å hente siste aktivitetskrav (med evt vurdering og varsel) for en liste personer.
- ta i bruk bulk-endepunkt herfra for alle personer med aktivt aktivitetskrav (basert på de reglene og feltene vi har her i dag)
Og hvis det funker bra: 
- lage ny `aktivitetskrav_aktiv_vurdering`-kolonnene som settes i vurdering-konsumenten og i migrereringsscript basert på reglene vi har i spørringen for enhetens oversikt i dag.
- tilpasse spørringene for enhetens oversikt til å bruke nytt felt og slette de andre kolonnene for …
> IS-2497: Inkluderer status NY_VURDERING for aktivitetskrav ved henting av personer til oversikten

- src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt
- src/test/kotlin/no/nav/syfo/testutil/TestApiModule.kt
Henter siste aktivitetskrav-vurdering fra isaktivitetskrav for alle personer med aktivt aktivitetskrav basert på "gammel" logikk.
Hvis dette kjører fint i prod ytelsesmessig kan vi migrere slik at alle med aktivt aktivitetskrav basert på "gammel" logikk får satt det nye feltet isAktivAktivitetskrav til true og deretter fjerne all bruk av gamle felter.
> IS-2596: Include all active aktivitetskrav in api call

- src/main/kotlin/no/nav/syfo/personstatus/application/manglendemedvirkning/ManglendeMedvirkningDTO.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/KafkaModule.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/manglendemedvirkning/ManglendeMedvirkningVurderingConsumer.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/manglendemedvirkning/VurderingRecord.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/manglendemedvirkning/ManglendeMedvirkningVurderingConsumerSpek.kt
- src/test/kotlin/no/nav/syfo/testutil/mock/ManglendeMedvirkningMock.kt
Oppdaget at de brukerne som har forhåndsvarsel på manglende medvirkning ikke dukket opp i oversikten. Vi fant ut at det var flere grunner til dette. For å fikse dette så har vi: 
- Startet consumeren 
- Gjort om personident til string
- Lagt til unntak som vurderingstype
- Fikset opp i copy paste feil, bruker nå vurderingRecord isteden
- Fikset opp i skrivemåte av svarfrist (svarFrist) i recorden
- Oppdaterte manglendeMedvirkningDTO til å passe produseren ved å endre til `vurderingType`, legge til `veilederident`. Har ignorert `document` som også leveres av api-et, men er ikke relevant her.
> IS-2679: Start consumer manglende medvirkning

- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt
- src/main/kotlin/no/nav/syfo/personstatus/api/v2/model/PersonOversiktStatusDTO.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/aktivitetskrav/AktivitetskravDTO.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/aktivitetskrav/IAktivitetskravClient.kt
- src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/aktivitetskrav/AktivitetskravClient.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/manglendemedvirkning/ManglendeMedvirkningClient.kt
- src/test/kotlin/no/nav/syfo/aktivitetskravvurdering/kafka/AktivitetskravVurderingConsumerSpek.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/ArbeidsuforhetvurderingConsumerSpek.kt
- src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/manglendemedvirkning/ManglendeMedvirkningVurderingConsumerSpek.kt
- src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/meroppfolging/SenOppfolgingKandidatStatusConsumerSpek.kt
- src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt
- src/test/kotlin/no/nav/syfo/testutil/TestApiModule.kt
- src/test/kotlin/no/nav/syfo/testutil/mock/AktivitetskravMock.kt
- src/test/kotlin/no/nav/syfo/testutil/mock/MockHttpClient.kt
Lagt til sjekk på aktivitetskrav-vurdering i api-test og lagt til manglende mock for `aktivitetskravClient` slik at testen passerer.
Flyttet også aktivitetskrav-filer til egne mapper slik at strukturen blir mer lik andre clients.
> Improve test and aktivitetskravClient mock

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktOppgaverService.kt
- src/main/kotlin/no/nav/syfo/personstatus/api/v2/endpoints/PersonOversiktStatusApiV2.kt
- src/main/kotlin/no/nav/syfo/personstatus/api/v2/model/PersonOversiktStatusDTO.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/PersonoversiktAktiveOppgaver.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/meroppfolging/IMeroppfolgingClient.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/meroppfolging/SenOppfolgingKandidatDTO.kt
- src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/ClientEnvironment.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/meroppfolging/MerOppfolgingClient.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt
- src/test/kotlin/no/nav/syfo/testutil/TestApiModule.kt
- src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt
- src/test/kotlin/no/nav/syfo/testutil/mock/MerOppfolgingMock.kt
- src/test/kotlin/no/nav/syfo/testutil/mock/MockHttpClient.kt
Tar i bruk bulk-endepunkt i ismeroppfolging for å hente sen oppfolging-kandidater for personer med aktiv sen oppfolging-kandidat.
> IS-2727: Use sen fase bulk endpoint

- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/personstatus/PersonTildelingService.kt
- src/main/kotlin/no/nav/syfo/personstatus/api/v2/ApiModule.kt
- src/main/kotlin/no/nav/syfo/personstatus/api/v2/endpoints/PersonTildelingApiV2.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/IPersonOversiktStatusRepository.kt
- src/main/kotlin/no/nav/syfo/personstatus/db/createOrUpdatePersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/domain/VeilederBrukerKnytningListe.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/behandlendeenhet/PersonBehandlendeEnhetService.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt
- src/main/resources/db/migration/V18_01__add_veileder_historikk.sql
- src/test/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersontildelingApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt
- src/test/kotlin/no/nav/syfo/testutil/TestApiModule.kt
- src/test/kotlin/no/nav/syfo/testutil/TestDatabase.kt
- src/test/kotlin/no/nav/syfo/testutil/UserConstants.kt
Nå tror jeg dette begynner å bli bra: database-scriptet initialiserer med eksisterende veilederknytninger, og når det gjøres nye tildelinger skal de bli lagret i den nye historikk-databasetabellen. Måtte refaktorere for å være sikker på at vi alltid har en eksisterende forekomst med enhetstilknytning først (siden det også blir med i historikken), dvs før tildelingen til veileder gjøres. Siden dette nå kan gjøres fra syfomodiaperson har vi utgangspunktet ingen garanti for at det finnes en rad i personoversikt-tabellen før tildelingen gjøres.
API kommer i en egen PR tenkte jeg.
> IS-2711: Veileder historikk

- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktSearchApiSpek.kt
- src/test/kotlin/no/nav/syfo/personstatus/infrastructure/database/PersonOversiktStatusRepositorySpek.kt
Veileder skal kunne søke opp sykmeldte personer. Legger derfor til sjekk i sql-spørringen på at sluttdato på oppfølgingstilfellet ikke er mer enn 16 dager siden, da regner vi oppfølgingstilfellet som aktivt og personen som sykmeldt.
> IS-2794: Add active oppfolgingstilfelle clause to search query

- src/main/resources/db/migration/V18_04__oppfolgingstilfelle_end_index.sql
Lager indeks på denne kolonnen som brukes til å sjekke at person har aktivt oppfølgingstilfelle (er sykmeldt) i søket.
> IS-2794: Index oppfolgingstilfelle_end

- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt
- src/test/kotlin/no/nav/syfo/personstatus/infrastructure/database/PersonOversiktStatusRepositorySpek.kt
Vi avklarte at vi ønsker at søket også skal inkludere personer som har aktiv oppgave i oversikten, ikke bare personer med aktivt oppfølgingstilfelle.
> IS-2829: Include persons with active oppgave in search query

- src/main/resources/db/migration/V18_07__fix_aktiv_arbeidsuførhet_vurdering.sql
- Setter arbeidsuforhet vurdering til inaktiv. 
- Ses i sammenheng med [denne](https://github.com/navikt/isarbeidsuforhet/pull/107#issuecomment-2500375985)
> IS-2824: Set arbeidsuforhet vurdering to inactive due to wrong vurdering

- src/main/kotlin/no/nav/syfo/personstatus/application/PersonoversiktStatusService.kt
- src/main/kotlin/no/nav/syfo/personstatus/db/createOrUpdatePersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
Fjerner oppdatering av navn i databasen som gjøres ifm api-kall siden vi nå oppdaterer navn via cronjob og konsumering av oppfølgingstilfeller.
Loggingen som var lagt på her sa at det kommer noen kall hver dag hvor 1-2 personer mangler navn, så for disse må vi fortsatt kalle pdl for å få med navn i responsen til frontend.
> Remove logging, counting and update name in db from api call

- src/main/kotlin/no/nav/syfo/personstatus/api/v2/model/PersonOversiktStatusDTO.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/PersonoversiktAktiveOppgaver.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/PersonoversiktOppgaverService.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/oppfolgingsoppgave/IOppfolgingsoppgaveClient.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/oppfolgingsoppgave/OppfolgingsoppgaveDTO.kt
- src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/oppfolgingsoppgave/OppfolgingsoppgaveClient.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/testutil/mock/OppfolgingsoppgaveMock.kt
Tatt i bruk nytt endepunkt for å hente aktive oppfølgingsoppgaver som er implementert i følgende [PR](https://github.com/navikt/ishuskelapp/pull/85).
Jeg valgte å beholde de eksisterende typene for oppfølgingsoppgave, men at det gjøres en transformasjon fra ny datamodell til den som allerede eksisterer tidligst mulig (mao. etter kall på ws).
> IS-2460: Tatt i bruk nytt endepunkt for å hente aktive oppfølgingsoppgaver

- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/oppfolgingsoppgave/OppfolgingsoppgaveClient.kt
Opprydding ifm. refaktorering av versjoner for oppfølgingsoppgave. Det ble endret i følgende PR: https://github.com/navikt/ishuskelapp/pull/86. Nåværende implementasjon av endepunktene `get-oppfolgingsoppgaver` og `get-oppfolgingsoppgaver-new` er nå helt identiske og dermed er det ikke lenger behov for å bruke det midlertidige endepunktet. Eksisterende implementasjon av begge finnes [her](https://github.com/navikt/ishuskelapp/blob/master/src/main/kotlin/no/nav/syfo/api/endpoints/OppfolgingsoppgaveApi.kt#L121-L183) (Det vil komme en siste PR som da sletter det ekstra endepunktet fra ishuskelapp)
> IS-2460: Endret tilbake til det originale endepunktet siden disse er nå helt identiske og det midlertidige skal fjernes

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/ClientEnvironment.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/veileder/VeilederClient.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/veileder/VeilederDTO.kt
- src/test/kotlin/no/nav/syfo/personstatus/infrastructure/clients/veileder/VeilederClientSpek.kt
- src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt
- src/test/kotlin/no/nav/syfo/testutil/UserConstants.kt
- src/test/kotlin/no/nav/syfo/testutil/mock/MockHttpClient.kt
- src/test/kotlin/no/nav/syfo/testutil/mock/SyfoveilederMock.kt
Slik at vi kan sjekke om veilder har sluttet og fjerne veiledertildeling.
Laget client for å kalle endepunkt i syfoveileder for å sjekke om veileder finnes/er enabled. Se relatert PR i syfoveileder: https://github.com/navikt/syfoveileder/pull/121
Tenkte å fortsette med PR som tar i bruk clienten fra kode som konsumerer oppfølgingstilfeller.
> IS-2260: VeilederClient

- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonMetric.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/OppfolgingstilfelleService.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/veileder/VeilederDTO.kt
- src/test/kotlin/no/nav/syfo/testutil/ExternalMockEnvironment.kt
Begynner med å logge og telle når vi konsumerer oppfølgingstilfelle for person og tildelt veileder ikke finnes eller ikke er enabled. Kommer ny PR som fjerner veileder-knytningen for disse tilfellene.
> IS-2260: Check tildelt veileder when updating person oppfolgingstilfelle

- src/main/kotlin/no/nav/syfo/personstatus/application/OppfolgingstilfelleService.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/OppfolgingstilfelleConsumerSpek.kt
- src/test/kotlin/no/nav/syfo/testutil/UserConstants.kt
- src/test/kotlin/no/nav/syfo/testutil/mock/SyfoveilederMock.kt
Gjør sjekk på en persons tildelte veileder når det kommer inn oppdateringer på oppfølgingstilfelle.
Dersom veileder ikke finnes eller ikke er enabled fjerner vi tildelingen slik at person ikke er tildelt veileder som har sluttet når det kommer ny oppgaver/hendelser på personen.
> IS-2260: Remove tildelt veileder if not found or enabled when updating oppfølgingstilfelle

- src/main/kotlin/no/nav/syfo/personstatus/application/aktivitetskrav/AktivitetskravDTO.kt
- Legger til `INNSTILLING_OM_STANS` til aktivitetskrav statuser.
> IS-1801: Add innstilling om stans status to dto

- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktSearchApiSpek.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/testutil/generator/OppfolgingstilfelleGenerator.kt
For å kunne vise kolonne for Virksomhet i søkeresultatet må vi hente virksomhetsnummer og -navn fra egen databasetabell for alle personer i søkeresultatet og legge det til `personOppfolgingstilfelleVirksomhetList` i domeneobjektet slik at det blir med ut i dtoen fra APIet.
> IS-2892: Get OppfolgingstilfelleVirksomhet for search result persons

- src/main/kotlin/no/nav/syfo/personstatus/application/IPersonOversiktStatusRepository.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/PersonBehandlendeEnhetService.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/oppfolgingsoppgave/OppfolgingsoppgaveService.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/behandlendeenhet/PersonBehandlendeEnhetCronjob.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/KafkaModule.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/behandlendeenhet/BehandlendeEnhetConsumer.kt
- src/test/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/BehandlerdialogPersonoversiktStatusApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/DialogmotekandidatPersonoversiktStatusApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/personstatus/application/PersonBehandlendeEnhetServiceSpek.kt
- src/test/kotlin/no/nav/syfo/testutil/ExternalMockEnvironment.kt
- src/test/kotlin/no/nav/syfo/testutil/mock/SyfobehandlendeenhetMock.kt
- Legger til kafka consumer som lytter på `teamsykefravr.behandlendeenhet` topicet som det blir produsert til når oppfølgingsenhet blir endret i `syfobehandlendeenhet`.
Se [tilhørende PR](https://github.com/navikt/syfobehandlendeenhet/pull/172) i `syfobehandlendeenhet`
> IS-3142: Add consumer for updating oppfolgingsenhet changes

- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/identhendelse/kafka/IdenthendelseConsumerService.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/IPersonOversiktStatusRepository.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/oppfolgingsoppgave/OppfolgingsoppgaveService.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/queries/getFromPersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/KafkaModule.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/oppfolgingsoppgave/OppfolgingsoppgaveConsumer.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/oppfolgingsoppgave/OppfolgingsoppgaveTask.kt
- src/test/kotlin/no/nav/syfo/oppfolgingsoppgave/kafka/OppfolgingsoppgaveConsumerSpek.kt
- Flytter noen queries inn i `PersonOversiktStatusRepository`
- Fjerner `DatabaseInterface` bruk fra `OppfolgingsoppgaveService`
- Flytter mer av håndtering av records inn i `OppfolgingsoppgaveConsumer`
Ikke sikkert alle endringer er så enkle å lese, så si ifra så kan vi se på PR'en sammen heller 🙌
> IS: Refactor oppfolgingsoppgaveservice

- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/behandlendeenhet/BehandlendeEnhetClient.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/CronjobModule.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/reaper/ReaperCronjob.kt
- src/test/kotlin/no/nav/syfo/cronjob/reaper/ReaperCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/testutil/ExternalMockEnvironment.kt
Nuller oppfølgingsenhet samtidig med at vi nuller veileder. 
Gjør kallet til syfobehandlendeenhet i alle fall, men hvis det ikke er satt noen oppfølgingsenhet der vil det ikke skje noe. Men hvis den er satt vil vi få et nytt innslag i syfobehandlendeenhet som gjør at vi reverterer tilbake til geografisk enhet.
> Oppfolgingsenhet nulling

- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/reaper/ReaperCronjob.kt
Det er en lang backlog her og cronjob'en slik den er nå går for sakte. Men undøvendig å unset'e oppfølgingsenhet for over en million gamle tilfeller her, så gjøre bare det for de som har tildelt veileder.
> IS-3304: Bare nulle oppfolgingsenhet when veileder

- src/main/kotlin/no/nav/syfo/personstatus/application/IPersonOversiktStatusRepository.kt
- src/main/kotlin/no/nav/syfo/personstatus/application/PersonoversiktStatusService.kt
- src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/queries/createOrUpdatePersonOversiktStatus.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/KafkaModule.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/kartleggingssporsmal/KartleggingssporsmalKandidatConsumer.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/oppfolgingsenfase/KandidatStatusRecord.kt
- src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/oppfolgingsenfase/SenOppfolgingKandidatStatusConsumer.kt
- src/test/kotlin/no/nav/syfo/personstatus/infrastructure/database/PersonOversiktStatusRepositoryTest.kt
- src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/meroppfolging/SenOppfolgingKandidatStatusConsumerTest.kt
- Legger til consumer for å ta i mot kartleggingsspørsmål fra topic som `ismeroppfolging` produserer til og oppdaterer db slik at kartleggingsspørsmål vurdering blir aktiv og derfor kan vises i oversikten.
Gjenstår å lande hvordan man setter vurdering til aktiv fra record. La inn kommentar på dette.
Se [tilhørende PR](https://github.com/navikt/ismeroppfolging/pull/140) i `ismeroppfolging`
> IS-3449-3: Consumer for kartleggingssporsmal vurdering endring
