src/test/kotlin/no/nav/syfo/SelftestSpek.kt, src/test/kotlin/no/nav/syfo/auth/AuthTokenSpek.kt, src/test/kotlin/no/nav/syfo/kafka/KafkaITSpek.kt, src/test/kotlin/no/nav/syfo/oversikthendelsetilfelle/OversikthendelstilfelleServiceSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/OversiktHendelseServiceSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusApiSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/PersontildelingApiSpek.kt
Replace depreacted spek funftions shouldEqual with shouldBeEqualTo and shouldNotEqual with shouldNotBeEqualTo
=> Replace deprecated spek functions

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
- Privison AzuerAD v2 with azureator
- Grant syfooversikt access to API
=> Add provisioning of AzureAD V2 in NAIS spec

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Remove deprecated ingress that is longer in use by any consumers.
=> Remove deprecated ingress

src/main/kotlin/no/nav/syfo/oversikthendelsetilfelle/PersonOppfolgingstilfelleHendelseQueries.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonOversiktStatusAksesseringQueries.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonOversiktStatusHendelseAksesseringQueries.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/util/DateUtil.kt, src/main/resources/db/migration/V11_3__add_tilfelt_enhet_updated_at.sql, src/test/kotlin/no/nav/syfo/oversikthendelsetilfelle/OversikthendelstilfelleServiceSpek.kt
Add column to store information about when tildelt_enhet was last updated for each person.
=> Add colum tildelt_enhet_updated_at to table PERSON_OVERSIKT_STATUS

src/main/kotlin/no/nav/syfo/application/ApplicationEnvironmentKafka.kt, src/main/kotlin/no/nav/syfo/application/kafka/KafkaConfig.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePerson.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonConfig.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonDeserializer.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonTask.kt
Add basic Kafka Aiven setup and config for comsuning OppfolgingstifellePerson.
=> Set up Kafka consumer for OppfolgingstilfellePerson

src/main/kotlin/no/nav/syfo/personstatus/PersonOppfolgingstilfelleVirksomhetQuery.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonOversiktStatusHendelseAksesseringQueries.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/test/kotlin/no/nav/syfo/personstatus/KafkaOppfolgingstilfellePersonServiceSpek.kt, src/test/kotlin/no/nav/syfo/testutil/UserConstants.kt, src/test/kotlin/no/nav/syfo/testutil/generator/KafkaOppfolgingstilfellePersonGenerator.kt
If VirksomhetsList of latest OppfolgingstilfellePerson is updated, then delete Virksomhet if no longer in latest OppfolgstilfellePerson, keep Virksomhet if in both exisiting and new OppfolgingstilfellePerson, and create new Virksomhet for new Virksomhet already exisiting in OppfolgingstilfellePerson.
=> Fix persistence of latest PersonOppfolgingstilfelleVirksomhetList

.nais/naiserator-prod.yaml
Completed processing of OppfolgingstilfellePerson of dev and it looks ready to be turned in Prod.
=> Enable processing of OppfolgingstilfellePerson in Prod.

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/cronjob/Cronjob.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobResult.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobRunner.kt, src/main/kotlin/no/nav/syfo/cronjob/leaderelection/LeaderPodClient.kt, src/main/kotlin/no/nav/syfo/cronjob/leaderelection/LeaderPodDTO.kt, src/main/kotlin/no/nav/syfo/cronjob/virksomhetsnavn/PersonOppfolgingstilfelleVirksomhetnavnCronjob.kt, src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt
Add cronjob setup to request virksomhetsnavn of PersonOppfolgingstilfelle asynchronously on recurring intervals.
=> Add cronjob setup for Virksomhetnavn

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/KafkaDialogmotekandidatEndring.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/KafkaDialogmotekandidatEndringMetric.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/KafkaDialogmotekandidatEndringService.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePerson.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonOversiktStatusAksesseringQueries.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonOversiktStatusHendelseAksesseringQueries.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/KOversikthendelse.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt, src/main/resources/db/migration/V11_7__add_column_dialogmotekandidat_generated_at.sql, src/test/kotlin/no/nav/syfo/dialogmotekandidat/kafka/KafkaDialogmotekandidatEndringServiceSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/KafkaOppfolgingstilfellePersonServiceSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/generator/KafkaDialogmotekandidatEndringGenerator.kt
Oppretter/oppdaterer PersonOversiktStatus med kandidat-flagg og timestamp hvis endring er nyere enn siste lagret timestamp
=> Consumer dialogmotekandidat-endring topic

build.gradle.kts, src/main/kotlin/no/nav/syfo/App.kt
Also set wait=true due to bump of ktor to version 2.0.1
=> Bump dependency versions to latest

.nais/naiserator-prod.yaml
=> Set initital startup delay and pod count back to normal

.github/workflows/kafka.yaml, .nais/kafka/dev.json, .nais/kafka/oversikthendelse.yaml, .nais/kafka/prod.json
Co-authored-by: June Henriksen <june.henriksen2@nav.no>
=> Add kafka topic oversikthendelse

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePerson.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt, src/main/kotlin/no/nav/syfo/personstatus/db/createOrUpdatePersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt
Too many details make it harder to read.
Co-authored-by: John Martin Lindseth <john.martin.lindseth@nav.no>
=> [kaizen] Remove Person from domain name

src/main/kotlin/no/nav/syfo/personoppgavehendelse/kafka/PersonoppgavehendelseService.kt, src/main/kotlin/no/nav/syfo/personstatus/db/UpdatePersonOversiktStatusColumn.kt, src/test/kotlin/no/nav/syfo/personoppgavehendelse/kafka/PersonoppgavehendelseServiceSpek.kt
Co-authored-by: June Henriksen <june.henriksen2@nav.no>
=> Update Personoversikt if hendelse type is dialogmotesvar

src/main/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetQuery.kt, src/main/kotlin/no/nav/syfo/cronjob/virksomhetsnavn/PersonOppfolgingstilfelleVirksomhetsnavnQuery.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/db/getFromPersonOversiktStatus.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
Co-authored-by: June Henriksen <june.henriksen2@nav.no>
=> Get innbyggere with ubehandlet dialogmotesvar

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/kafka/KafkaAktivitetskravVurdering.kt, src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/kafka/KafkaAktivitetskravVurderingService.kt, src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/kafka/KafkaAktivitetskravVurderingTask.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/kafka/KafkaModule.kt, src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt
Turned off with toggled.
Nothing is done with the record yet.
=> Consume aktivitetskrav-vurdering topic.

src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/client/azuread/AzureAdClient.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt
En typo jeg kom over da jeg jobbet med identhendelse.
=> Refactor typo in azureEnvironment

src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/AktivitetskravService.kt, src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/domain/Aktivitetskrav.kt, src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/kafka/KafkaAktivitetskravVurdering.kt, src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/kafka/KafkaAktivitetskravVurderingConsumer.kt, src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/kafka/KafkaAktivitetskravVurderingTask.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/KafkaDialogmotekandidatEndring.kt, src/main/kotlin/no/nav/syfo/dialogmotestatusendring/domain/DialogmoteStatusendring.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePerson.kt, src/main/kotlin/no/nav/syfo/personstatus/db/UpdatePersonOversiktStatusColumn.kt, src/main/kotlin/no/nav/syfo/personstatus/db/createOrUpdatePersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/KOversikthendelse.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt, src/test/kotlin/no/nav/syfo/aktivitetskravvurdering/AktivitetskravServiceSpek.kt, src/test/kotlin/no/nav/syfo/testutil/generator/PPersonOversiktStatusGenerator.kt
Store new PersonOversitkStatus if it doesn't exist on the innbygger.
Update with info about aktivitetskrav if row already exists.
No change to P object, that will be changed later when we add aktivitetskrav to fetching.
=> Process AktivitetskravVurdering from kafka

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/api/authentication/ApiFeature.kt, src/main/kotlin/no/nav/syfo/kafka/KafkaTask.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
Ser at Grafana melder om mange 5xx-feil, men finner ikke noe i loggen.
Har ikke helt forstått hva som forårsaker dette, men forsøker å tilpasse logg-oppsettet til slik vi har det i andre app'er - kanskje det hjelper.
=> 5xx-feil blir ikke logget

src/main/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetQuery.kt
Still update everyone each day.
Only people with active task are updated.
=> Update enhet for innbyggere who has never changed enhet in database

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt, src/main/kotlin/no/nav/syfo/client/pdl/PdlPersonidentNameCache.kt, src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseTask.kt, src/main/kotlin/no/nav/syfo/kafka/KafkaModule.kt, src/main/kotlin/no/nav/syfo/pdlpersonhendelse/PdlPersonhendelseService.kt, src/main/kotlin/no/nav/syfo/pdlpersonhendelse/db/PersonhendelseQueries.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/PersonOversiktStatusApiV2.kt, src/main/kotlin/no/nav/syfo/personstatus/db/createOrUpdatePersonOversiktStatus.kt, src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersontildelingApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testutil/TestApiModule.kt
This reverts commit 8ed7e31f9a69f204f028d17264d5ad7a9a8e81e6.
=> Revert "Fetch names from PDL and store in db (#191)"

src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt
=> Don't query pdl if identlist is empty

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/kafka/KafkaModule.kt, src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt
Venter på https://github.com/navikt/syfooversiktsrv/pull/191
=> Toggle on Personhendelse Kafka-consumer in prod

src/main/kotlin/no/nav/syfo/application/database/Database.kt
Ser ut som dette har fungert bra i isdialogmelding, så synes vi skal forsøke det her også (siden det har vært en del restarts pga db-konflikter de siste dagene).
=> Bruk isolasjonsnivå READ_COMMITTED

src/main/kotlin/no/nav/syfo/personstatus/api/v2/PersonOversiktStatusDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
This requires change in syfooversikt as well.
=> Use sistVurdert in PersonOversiktStatusDTO instead of updatedAt

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/PersonOversiktStatusApiV2.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/AktivitetskravPersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
Option to use a testveileder with a cutoff date for 7 days ago
=> Add cutoff date for aktivitetskrav

.nais/naiserator-prod.yaml
Opplever feil i prod, dette er en midlertidig løsning.
=> Untoggle aktivitetskravvurdering processing from kafka

src/test/kotlin/no/nav/syfo/personstatus/api/v2/AktivitetskravPersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt
Vi sjekker ikke lenger på oppfølgingstifelle i uthenting av aktivitetskrav (`isActiveAktivitetskrav`) så den biten kan fjernes fra testene.
=> Move aktivitetskrav-tests to separate file and remove tilfelle stuff

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/kafka/KafkaModule.kt, src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt
This reverts commit 965ba5cf06a2dc43f8e75032e3b7d07cc55f893e.
=> Revert "Enable identhendelse processing in prod (#237)"

src/main/kotlin/no/nav/syfo/identhendelse/IdenthendelseService.kt
Ser ut som det var litt copy+paste her fra andre apper
=> Refactor log message

src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql
Nytt forsøk på å gi tilgang til disykefravar (i praksis skal de bare bruke replica-instansen, men tror vi må grant'e i primærinstansen likevel).
=> Grant til disykefravar

src/main/resources/db/migration/V14_2__close_dialogmotesvar.sql
https://jira.adeo.no/browse/FAGSYSTEM-264428
=> Close dialogmotesvaroppgave

src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/AktivitetskravPersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/DialogmotekandidatPersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testutil/database/PersonoversiktStatusSetup.kt
AND test the same way for active aktivitetskrav at the application level as in the database level.
This should get rid of the Berit bug.
=> Use aktivitetskravfilter only for test veileder

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/client/ClientEnvironment.kt, src/main/kotlin/no/nav/syfo/client/oppfolgingstilfelle/OppfolgingstilfelleClient.kt, src/main/kotlin/no/nav/syfo/client/oppfolgingstilfelle/OppfolgingstilfellePersonDTO.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/aktivitetskrav/PersonAktivitetskravRepairCronjob.kt, src/main/kotlin/no/nav/syfo/cronjob/aktivitetskrav/PersonAktivitetskravRepairCronjobQueries.kt, src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt
=> Repair aktivitetskrav kandidater

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Tror dette vil fikse cronjob'en som Anders oppdaget at ikke virker lengre.
Vi har nok dette problemet flere steder så vi får rydde opp fortløpende. Tror det er fordelaktig å løse dette problemet med å ta i bruk service discovery (alternativet er å legge til den fulle ingressen for tjenesten man bruker som en external host).
=> Use service discovery

src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/reaper/ReaperCronjob.kt, src/main/kotlin/no/nav/syfo/cronjob/reaper/ReaperCronjobMetric.kt, src/main/kotlin/no/nav/syfo/cronjob/reaper/ReaperQueries.kt, src/main/kotlin/no/nav/syfo/cronjob/reaper/ReaperService.kt, src/test/kotlin/no/nav/syfo/cronjob/reaper/ReaperCronjobSpek.kt
If innbyggers tilfelle ended three months ago, remove tildelt veileder.
=> Add reaper cronjob that removes tildelt veileder

.editorconfig, build.gradle.kts, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseTask.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePerson.kt, src/main/kotlin/no/nav/syfo/pdlpersonhendelse/kafka/KafkaPersonhendelseTask.kt, src/main/kotlin/no/nav/syfo/personoppgavehendelse/kafka/PersonoppgavehendelseService.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/PersonTildelingApiV2.kt
Hindrer meg fra å pushe andre ting vedrørende personoppgave 🙃
=> Upgrade ktlint and apply changes

src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/domain/Aktivitetskrav.kt, src/main/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetQuery.kt, src/main/kotlin/no/nav/syfo/cronjob/virksomhetsnavn/PersonOppfolgingstilfelleVirksomhetsnavnQuery.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/KafkaDialogmotekandidatEndring.kt, src/main/kotlin/no/nav/syfo/dialogmotestatusendring/domain/DialogmoteStatusendring.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePerson.kt, src/main/kotlin/no/nav/syfo/personoppgavehendelse/kafka/PersonoppgavehendelseService.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/PersonOversiktStatusDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/db/UpdatePersonOversiktStatusColumn.kt, src/main/kotlin/no/nav/syfo/personstatus/db/createOrUpdatePersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/db/getFromPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/OversikthendelseType.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt, src/main/resources/db/migration/V14_6__add_column_behandlerdialog_ubehandlet.sql, src/test/kotlin/no/nav/syfo/personoppgavehendelse/kafka/PersonoppgavehendelseServiceSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testutil/generator/PPersonOversiktStatusGenerator.kt
Skal hente inn personoppgave fra topic, lagre i databasen, og blant annet hente ut det nye feltet når man slår opp i APIet i syfooversikt.
=> Receive personoppgave for ubehandlet behandlerdialog 

src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
Prøver å gå tilbake til CIO siden vi ikke merket noen bedring med Apache.
=> Revert "Use Apache instead of CIO (#278)"

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
This reverts commit 1439a0d6c3195ddcb2725cf151068f309ad5e2b9.
=> Revert "syfo-tilgangskontroll gcp (#286)"

src/main/resources/db/migration/V14_7__close_motebehov.sql
https://jira.adeo.no/browse/FAGSYSTEM-274664
=> Close motebehovoppgave

src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/preloadcache/PreloadCacheCronjob.kt, src/main/kotlin/no/nav/syfo/cronjob/preloadcache/PreloadCacheQueries.kt, src/test/kotlin/no/nav/syfo/cronjob/preloadcache/PreloadCacheCronjobSpek.kt, src/test/kotlin/no/nav/syfo/cronjob/preloadcache/PreloadCacheCronjobWithMockSpek.kt, src/test/kotlin/no/nav/syfo/testutil/generator/PPersonOversiktStatusGenerator.kt, src/test/kotlin/no/nav/syfo/testutil/generator/PersonOversiktStatusGenerator.kt, src/test/kotlin/no/nav/syfo/testutil/mock/VeilederTilgangskontrollMock.kt
Har ikke laget preloadbrukere-tjenesten i syfo-tilgangskontroll, så må gjøre det før denne kan merges.
=> Preload tilgangskontroll cache every morning

src/main/kotlin/no/nav/syfo/App.kt
Deploy gikk ikke gjennom: https://github.com/navikt/syfooversiktsrv/actions/runs/5890527893/job/15978501029
```kotlin
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property database has not been initialized
at no.nav.syfo.application.database.DatabaseModuleKt.getDatabase(DatabaseModule.kt:7)
at no.nav.syfo.AppKt.main(App.kt:50)
at no.nav.syfo.AppKt.main(App.kt)
```
`database` er en lateinit variabel og blir ikke satt før i `databaseModule`.
Tror dette skal funke, kan jo deploye til dev først denne gangen da før jeg merger ;) 🤠
=> Initialize service after databasemodule is run

src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/domain/Aktivitetskrav.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/AktivitetskravPersonoversiktStatusApiV2Spek.kt
Ny aktivitetskrav-status ifm høstdugnad 🍂
=> Add LUKKET status

.nais/naiserator-prod.yaml
Vi hadde glemt å slå på i prod 🙃
=> IS-1646: Turn on toggle for huskelapp

src/main/resources/db/migration/V15_4__close_motebehov.sql
Manuell lukking av to møtebehov som står som oppgaver, selv om de er behandlet. JML har gravd litt i dette også, men ikke funnet ut hvorfor det ikke ble oppdatert riktig hos oss. Vi får holde et øye med det. 
Se jirasaker:
- https://jira.adeo.no/browse/FAGSYSTEM-295563 
- https://jira.adeo.no/browse/FAGSYSTEM-295879
=> IS-1651: Behandle møtebehov that is actually behandlet

build.gradle.kts
Se https://github.com/navikt/syfooversiktsrv/security/dependabot/1 og https://nvd.nist.gov/vuln/detail/CVE-2022-1471 for sårbarhet. Det var vel en grunn til at vi var på 1.33 før, men litt usikker på hvordan jeg kan teste dette 🤔
Det er en fin kommando i gradle som heter `./gradlew -q dependencyInsight --dependency <dependency du vil sjekke>`, der man kan søke opp dependency og finne versjonen vi bruker, og hvilken pakke den er transitivt koblet til 🙌🏼
=> IS: Upgrade snakeyaml transitive dependency

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/client/ClientEnvironment.kt, src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/metric/Metrics.kt, src/test/kotlin/no/nav/syfo/cronjob/preloadcache/PreloadCacheCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testutil/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/mock/VeilederTilgangskontrollMock.kt
This reverts commit 808f40c6ee9f768b56dd867d5d79bca0885e3686.
=> Revert "IS-1686: Use new tilgangskontroll app (#328)"

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/client/ClientEnvironment.kt, src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/metric/Metrics.kt, src/test/kotlin/no/nav/syfo/cronjob/preloadcache/PreloadCacheCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testutil/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/mock/VeilederTilgangskontrollMock.kt
This reverts commit 2c7210da7df8b3068b3fee059c9b879e49e677a6.
Bytter til ny tilgangskontroll igjen. Vi kan merge denne litt utpå dagen, når det ikke er så mange på jobb. Og så kjøres preloading av cache i morgen, slik at oversikten forhåptengigvis lastes raskere 🤞
=> Revert "Revert "IS-1686: Use new tilgangskontroll app (#328)" (#331)"

src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/domain/Aktivitetskrav.kt
Legger til aktivitetskrav status NY_VURDERING
=> IS-1749: Add aktivitetskrav status NY_VURDERING

src/main/kotlin/no/nav/syfo/cronjob/preloadcache/PreloadCacheIstilgangskontrollCronjob.kt
Vi ønsker å redeploye poddene slik at de kaller preloadingen på nytt.
=> Update initialdelay to test preloading of cache in istilgangskontroll

src/main/kotlin/no/nav/syfo/cronjob/preloadcache/PreloadCacheIstilgangskontrollCronjob.kt
Run preloading for both new and old app untill we only use new app for tilgangskontroll.
=> IS-1686: Preload istilgangskontroll at 6am

src/main/kotlin/no/nav/syfo/personstatus/api/v2/PersonOversiktStatusDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/db/UpdatePersonOversiktStatusColumn.kt, src/main/kotlin/no/nav/syfo/personstatus/db/createOrUpdatePersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/db/getFromPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/trengeroppfolging/TrengerOppfolgingService.kt, src/main/kotlin/no/nav/syfo/trengeroppfolging/domain/TrengerOppfolging.kt, src/main/kotlin/no/nav/syfo/trengeroppfolging/kafka/KafkaHuskelapp.kt, src/main/resources/db/migration/V15_7__add_trenger_oppfolging_frist.sql, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testutil/generator/KafkaHuskelappGenerator.kt, src/test/kotlin/no/nav/syfo/testutil/generator/PPersonOversiktStatusGenerator.kt, src/test/kotlin/no/nav/syfo/trengeroppfolging/kafka/TrengerOppfolgingConsumerSpek.kt
Lagrer frist knyttet til trenger oppfølging slik at det kan vises i syfooversikt
=> IS-1710: Trenger oppfolging frist

src/main/kotlin/no/nav/syfo/trengeroppfolging/domain/TrengerOppfolging.kt, src/main/kotlin/no/nav/syfo/trengeroppfolging/kafka/KafkaHuskelapp.kt, src/test/kotlin/no/nav/syfo/testutil/generator/KafkaHuskelappGenerator.kt, src/test/kotlin/no/nav/syfo/trengeroppfolging/kafka/TrengerOppfolgingConsumerSpek.kt
Når trenger oppfølging blir satt inaktiv vil vi også nulle ut fristen her.
=> IS-1710: Null frist when not active

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/Oppfolgingstilfelle.kt
Vi har undersøkt en del tilfeller med negativ varighet og sett at det gjelder tilfeller som starter noen dager/uke frem i tid (stemmer det @geir-waagboe ?). Regner ikke det som en feilsituasjon vi trenger å undersøke nærmere så endrer derfor til warning her.
=> Change to log level warning when negative varighet oppfolgingstifelle

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, build.gradle.kts, src/test/kotlin/no/nav/syfo/cronjob/reaper/ReaperCronjobSpek.kt
Oppgradert avhengigheter, fikset sårbarheter og fikset en test som feilet lokalt pga tidssone.
=> Bump dependencies and fix test that fails locally

src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt, src/main/kotlin/no/nav/syfo/util/RequestUtil.kt
- Legger til `behandlingsnummer` header
=> IS-1477: Add behandlingsnummer header to pdl requests.

src/main/kotlin/no/nav/syfo/client/ereg/EregClient.kt
Ser det hadde kommet masse feillogger på dette https://logs.adeo.no/app/r/s/oYp18. Geir fikset tilsvarende i isdialogmote https://github.com/navikt/isdialogmote/pull/500/files.
Vet ikke hvorfor dette dukket opp nå? Koden er gammel.
=> Fix ereg path

src/main/kotlin/no/nav/syfo/frisktilarbeid/kafka/KafkaFriskTilArbeidMetric.kt, src/main/kotlin/no/nav/syfo/frisktilarbeid/kafka/KafkaFriskTilArbeidService.kt, src/main/kotlin/no/nav/syfo/frisktilarbeid/kafka/KafkaFriskTilArbeidTask.kt, src/main/kotlin/no/nav/syfo/frisktilarbeid/kafka/VedtakFattetRecord.kt, src/main/kotlin/no/nav/syfo/kafka/KafkaModule.kt, src/main/kotlin/no/nav/syfo/personoppgavehendelse/kafka/PersonoppgavehendelseConsumer.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/db/UpdatePersonOversiktStatusColumn.kt, src/main/kotlin/no/nav/syfo/personstatus/db/createOrUpdatePersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/db/getFromPersonOversiktStatus.kt, src/test/kotlin/no/nav/syfo/frisktilarbeid/kafka/KafkaFriskTilArbeidServiceSpek.kt, src/test/kotlin/no/nav/syfo/testutil/TestKafkaModule.kt, src/test/kotlin/no/nav/syfo/testutil/generator/KafkaFriskTilArbeidGenerator.kt
Kafka-consumer som oppdaterer dato-kolonnen for friskmelding til arbeidsformidling.
=> IS-2274: Kafka-consumer

src/main/resources/db/migration/V16_2__close_motebehov.sql
Fjerner motebehov på saker `IS-2291` og `IS-2209`
=> IS-2291-2209: Close motebehov

src/main/resources/db/migration/V16_3__close_motebehov.sql
=> IS-2369: Close motebehov

src/main/resources/db/migration/V16_6__adjust_person_oversikt_status_enheter_oversikt_index.sql
- Legger til index som ble [glemt i forrige PR](https://github.com/navikt/syfooversiktsrv/pull/365)
=> IS-2271: Add friskmelding_til_arbeidsformidling_fom to index

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/identhendelse/IdenthendelseService.kt, src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseTask.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/endpoints/PersonOversiktStatusApiV2.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/azuread/AzureAdClient.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/pdl/PdlClient.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt, src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/PersonOversiktStatusRepositorySpek.kt, src/test/kotlin/no/nav/syfo/testutil/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/TestApiModule.kt
Det virker som at selve package-deklarasjonen til `PdlClient` ikke oppdaterte seg i Vetle sin refactoring-PR, av en eller annen grunn. Så jeg fikset det, pluss begynte å se litt på andre ting man kunne forbedre. Synes mye av koden i `PersonoversiktStatusService` er litt vanskelig å lese, men jeg fant ingen umiddelbare store forbedringer.
Lager PR for IS-1932 ut fra denne branchen.
=> IS: Refactoring

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/model/PersonOversiktStatusDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/application/oppfolgingsoppgave/IOppfolgingsoppgaveClient.kt, src/main/kotlin/no/nav/syfo/personstatus/application/oppfolgingsoppgave/OppfolgingsoppgaveDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/ClientEnvironment.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/arbeidsuforhet/ArbeidsuforhetvurderingClient.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/oppfolgingsoppgave/OppfolgingsoppgaveClient.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/ArbeidsuforhetvurderingConsumerSpek.kt, src/test/kotlin/no/nav/syfo/testutil/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/TestApiModule.kt, src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/mock/OppfolgingsoppgaveMock.kt
Kaller endepunktet i `ishuskelapp` for de personene som har `trengerOppfolging = true` i databasen.
På sikt vil vi kanskje slutte å lagre frist-dato i dben, og heller bruke det fra APIet?
=> IS-1932: Fetch oppfolgingsoppgaver when asking for persons in oversikten

src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/application/arbeidsuforhet/ArbeidsuforhetvurderingDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/application/arbeidsuforhet/IArbeidsuforhetvurderingClient.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/arbeidsuforhet/ArbeidsuforhetvurderingClient.kt, src/test/kotlin/no/nav/syfo/testutil/mock/ArbeidsuforhetvurderingMock.kt
Bruker nytt api for å hente flere arbeidsuførhetsvurderinger på en gang
=> IS-2437: arbeidsuforhetvurdering bulk

src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/db/PersonOppfolgingstilfelleVirksomhetQuery.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PPersonOppfolgingstilfelleVirksomhet.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testutil/generator/OppfolgingstilfelleGenerator.kt
Litt annerledes her enn før, siden man skal ha en liste med Int og ikke String. Funker bra i dev ✅
=> IS-2465: Get virksomhet for personstatus using bulk-select

src/main/kotlin/no/nav/syfo/frisktilarbeid/kafka/FriskTilArbeidVedtakConsumer.kt, src/main/kotlin/no/nav/syfo/frisktilarbeid/kafka/KafkaFriskTilArbeidTask.kt, src/test/kotlin/no/nav/syfo/frisktilarbeid/kafka/KafkaFriskTilArbeidServiceSpek.kt, src/test/kotlin/no/nav/syfo/testutil/TestKafkaModule.kt
- Endrer navngivning slik vi pleier å navngi kafka consumerne våre
=> IS: Rename to standard naming for kafka consumers

src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/model/PersonOversiktStatusDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/application/IPersonOversiktStatusRepository.kt, src/main/kotlin/no/nav/syfo/personstatus/db/createOrUpdatePersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/db/getFromPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/KafkaModule.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/meroppfolging/KandidatStatusRecord.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/meroppfolging/SenOppfolgingKandidatStatusConsumer.kt, src/main/resources/db/migration/V17_1__add_column_is_aktiv_sen_oppfolging_kandidat.sql, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/database/PersonOversiktStatusRepositorySpek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/meroppfolging/SenOppfolgingKandidatStatusConsumerSpek.kt, src/test/kotlin/no/nav/syfo/testutil/generator/PPersonOversiktStatusGenerator.kt
Konsumerer fra topic, lagrer i database som en upsert, og tilgjengeliggjør feltet i DTOen til oversikten.
=> IS-2363: Consume mer-oppfolging kandidat status

src/main/resources/db/migration/V17_3__add_column_is_aktiv_aktivitetskrav_vurdering.sql
- Legger til kolonne for å holde på om en person har et aktivt aktivitetskrav
=> IS-2329: Add column for aktiv aktivitetskrav vurdering

src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/oppfolgingsoppgave/OppfolgingsoppgaveClient.kt
- Legger til at vi håndterer 204 fra `/get-vurderinger` endepunkt i `ishuskelapp`
=> IS-2543: Handle 204 from ishuskelapp

src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt
- Nedgraderer log level til `warning`
=> IS: Downgrade log level to warning for no oppfolgingsoppgaver found

src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/behandlendeenhet/PersonBehandlendeEnhetQuery.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/virksomhetsnavn/PersonOppfolgingstilfelleVirksomhetsnavnQuery.kt
Lagt til flagg som manglet der vi finner personer med aktiv oppgave/hendelse for å oppdatere tildeltEnhet / virksomhetsnavn
=> IS-2618: Include missing flags in queries

src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt
- Legger til `FORHANDSVARSEL` på en sjekk om et aktivitetskrav er aktivt for en gitt person.
=> IS: Add FORHANDSVARSEL to check if aktivitetskrav is active

src/main/resources/db/migration/V17_4__migrate_is_aktiv_aktivitetskrav_vurdering.sql
Setter riktig verdi på `is_aktiv_aktivitetskrav_vurdering` basert på "gamle" felter.
=> IS-2596: Migrate is_aktiv_aktivitetskrav_vurdering

src/main/resources/db/migration/V17_8__drop_aktivitetskrav_columns.sql
Merges etter bruken er fjernet i https://github.com/navikt/syfooversiktsrv/pull/423
=> IS-2596: Drop aktivitetskrav columns no longer used

build.gradle.kts, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/ApiModule.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/AktivitetskravClient.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/arbeidsuforhet/ArbeidsuforhetvurderingClient.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/azuread/AzureAdClient.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/behandlendeenhet/BehandlendeEnhetClient.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/ereg/EregClient.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/oppfolgingsoppgave/OppfolgingsoppgaveClient.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/pdl/PdlClient.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/veiledertilgang/VeilederTilgangskontrollClient.kt, src/test/kotlin/no/nav/syfo/cronjob/preloadcache/PreloadCacheCronjobSpek.kt, src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/clients/azuread/AzureAdClientSpek.kt, src/test/kotlin/no/nav/syfo/testutil/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/TestApiModule.kt, src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/mock/ArbeidsuforhetvurderingMock.kt, src/test/kotlin/no/nav/syfo/testutil/mock/AzureAdMock.kt, src/test/kotlin/no/nav/syfo/testutil/mock/EregMock.kt, src/test/kotlin/no/nav/syfo/testutil/mock/MockHttpClient.kt, src/test/kotlin/no/nav/syfo/testutil/mock/MockUtils.kt, src/test/kotlin/no/nav/syfo/testutil/mock/OppfolgingsoppgaveMock.kt, src/test/kotlin/no/nav/syfo/testutil/mock/PdlMock.kt, src/test/kotlin/no/nav/syfo/testutil/mock/SyfobehandlendeenhetMock.kt, src/test/kotlin/no/nav/syfo/testutil/mock/VeilederTilgangskontrollMock.kt
Forenklet testoppsettet til å bruke Mock Engine (https://ktor.io/docs/client-testing.html#test-client) for å mocke respons fra clients tilsvarende slik vi gjør det i andre apper. Blir mer likt slik vi har det i de nyere appene våre og muligens litt raskere tester siden man slipper å startet opp en embedded server for hvert endepunkt som kalles i testene + litt mindre kode :)
=> Use Ktor Mock Engine

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/BackgroundTask.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/model/PersonOversiktStatusDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/application/manglendemedvirkning/IManglendeMedvirkningClient.kt, src/main/kotlin/no/nav/syfo/personstatus/application/manglendemedvirkning/ManglendeMedvirkningDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/ClientEnvironment.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/arbeidsuforhet/ArbeidsuforhetvurderingClient.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/manglendemedvirkning/ManglendeMedvirkningClient.kt, src/test/kotlin/no/nav/syfo/aktivitetskravvurdering/kafka/AktivitetskravVurderingConsumerSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/ArbeidsuforhetvurderingConsumerSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/manglendemedvirkning/ManglendeMedvirkningVurderingConsumerSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/meroppfolging/SenOppfolgingKandidatStatusConsumerSpek.kt, src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/TestApiModule.kt, src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/mock/ManglendeMedvirkningMock.kt, src/test/kotlin/no/nav/syfo/testutil/mock/MockHttpClient.kt
Henter informasjon fra ismanglendemedvirkning om de arbeidstakerne i enhetens oversikt som har det aktuelle flagget satt
=> IS-2595: Bulk manglende medvirkning

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktOppgaverService.kt, src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/ApiModule.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/endpoints/PersonOversiktStatusApiV2.kt, src/main/kotlin/no/nav/syfo/personstatus/application/PersonoversiktAktiveOppgaver.kt, src/test/kotlin/no/nav/syfo/aktivitetskravvurdering/kafka/AktivitetskravVurderingConsumerSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/ArbeidsuforhetvurderingConsumerSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/manglendemedvirkning/ManglendeMedvirkningVurderingConsumerSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/meroppfolging/SenOppfolgingKandidatStatusConsumerSpek.kt, src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/TestApiModule.kt
`PersonoversiktStatusService` har blitt stor så laget en egen service som tar seg av henting av informasjon om aktive oppgaver/vurderinger fra andre apper.
=> Flyttet kode for å hente aktive oppgaver/vurderinger til egen service

src/main/resources/db/migration/V18_00__close_outdated_motesvar.sql
Jira-sak om noen utdaterte motesvar-oppgaver. Må lukkes her og i ispersonoppgave.
=> IS-2735: Nullstill utdaterte motesvar-oppgaver

src/test/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetCronjobSpek.kt, src/test/kotlin/no/nav/syfo/cronjob/virksomhetsnavn/PersonOppfolgingstilfelleVirksomhetsnavnCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testutil/assertion/PPersonOppfolgingstilfelleVirksomhetAssertion.kt, src/test/kotlin/no/nav/syfo/testutil/assertion/PersonOversiktStatusDTOAssertion.kt
Endret tester slik at de ikke feiler på Windows. Gjorde også litt mindre refaktorering for litt å redusere bruk av if-else i tester i relaterte filer.
=> Fikset tester som feiler på windows samt gjort noe refaktorering

src/main/kotlin/no/nav/syfo/personstatus/PersonTildelingService.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/endpoints/PersonTildelingApiV2.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/model/VeilederHistorikkDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/model/VeilederTildelingHistorikkDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/application/IPersonOversiktStatusRepository.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt, src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersontildelingApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testutil/TestDatabase.kt
Api for å hente historikk for veiledertildelinger for en gitt arbeidstaker.
=> IS-2711: Veileder historikk api

src/main/kotlin/no/nav/syfo/personstatus/db/getFromPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/behandlendeenhet/PersonBehandlendeEnhetQuery.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/virksomhetsnavn/PersonOppfolgingstilfelleVirksomhetsnavnQuery.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt, src/main/resources/db/migration/V18_02__update_index_enhetens_oversikt.sql
Vi har definert denne sjekken på aktiv oppgave tre steder som man må huske å oppdatere når nye felter legges til. Tenkte derfor det var lurt å samle den i `PersonOversiktStatusRepository`. Åpen for andre/bedre forslag :)
=> IS-2805: Refactor aktiv oppgave query

src/main/resources/db/migration/V18_03__add_column_fodselsdato.sql
- Legger til `fodselsdato` kolonne i `person_oversikt_status` tabellen. Typen er `DATE` som virker riktig og fungerer bra med querying.
- Vi må tenke litt videre på når og hvordan vi ønsker å populere denne 🤔
=> IS-2804: Add fodselsdato column to db table

build.gradle.kts
Vi har en "critical vulnerability" her.
=> Bump dependency

src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktSearchService.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/ApiModule.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/endpoints/PersonOversiktStatusApiV2.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/model/SearchQueryDTO.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktSearchApiSpek.kt
Hva er nytt / hva har blitt fikset?
=> IS-2784: Initial api and service with access control

src/main/kotlin/no/nav/syfo/personstatus/api/v2/model/PersonOversiktStatusDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/db/createOrUpdatePersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/db/getFromPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/database/PersonOversiktStatusRepositorySpek.kt, src/test/kotlin/no/nav/syfo/testutil/generator/PPersonOversiktStatusGenerator.kt
Legger til `fodselsdato`-felt i alle modell-klasser. Denne er foreløpig `null` for alle vi har i databasen, se https://github.com/navikt/syfooversiktsrv/pull/468
=> IS-2803: Add fodselsdato to persistence/domain/dto classes

src/main/kotlin/no/nav/syfo/personstatus/api/v2/model/SearchQueryDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/SearchQuery.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktSearchApiSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/database/PersonOversiktStatusRepositorySpek.kt
Utvider api for søk med birthdate-parameter og tar denne i bruk i databasespørring
=> IS-2794: Add fodselsdato to search query

src/main/resources/db/migration/V18_05__name_index.sql
Legger på index på kolonnen for navn siden denne skal brukes i søket
=> IS-2794: Index name

src/main/resources/db/migration/V18_06__fix_aktiv_arbeidsuførhet_vurdering.sql
Denne fjerner oppgaven i oversikten etter at vi har fjerna vurderingen gjort på feil person ref [denne PRen](https://github.com/navikt/isarbeidsuforhet/pull/104#issuecomment-2491137339)
=> IS-2822: Fix aktiv arbeidsuførhet vurdering

src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/application/IPersonOversiktStatusRepository.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/PopulateNavnAndFodselsdatoCronjob.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/database/PersonOversiktStatusRepositorySpek.kt
- Legger til logging når cronjob `PopulateNavnAndFodselsdatoCronjob ` er ferdig med antall oppdaterte.
=> IS-2803: Added logging when cronjob is finished

src/main/kotlin/no/nav/syfo/personstatus/PersonoversiktStatusService.kt
I api-kallet som henter personer til oversikten gjør vi også kall til PDL for de som mangler navn og oppdaterer navn på disse i databasen. 
Tanken er at dette kan fjernes etter hvert nå som vi oppdaterer navn og fødselsdato i cronjobb og ved lesing av oppfølgingstilfeller. Lagt på noe logging og telling for å sjekke hvor ofte det skjer i prod.
=> Add metric and logging when updating names in api call

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/kafka/AktivitetskravVurderingConsumer.kt, src/main/kotlin/no/nav/syfo/aktivitetskravvurdering/kafka/KafkaAktivitetskravVurderingTask.kt, src/main/kotlin/no/nav/syfo/oppfolgingsoppgave/OppfolgingsoppgaveService.kt, src/main/kotlin/no/nav/syfo/oppfolgingsoppgave/kafka/OppfolgingsoppgaveTask.kt, src/main/kotlin/no/nav/syfo/personoppgavehendelse/kafka/KafkaPersonoppgavehendelseTask.kt, src/main/kotlin/no/nav/syfo/personoppgavehendelse/kafka/PersonoppgavehendelseConsumer.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/ApiModule.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/endpoints/PersonOversiktStatusApiV2.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/endpoints/PersonTildelingApiV2.kt, src/main/kotlin/no/nav/syfo/personstatus/application/PersonBehandlendeEnhetService.kt, src/main/kotlin/no/nav/syfo/personstatus/application/PersonTildelingService.kt, src/main/kotlin/no/nav/syfo/personstatus/application/PersonoversiktOppgaverService.kt, src/main/kotlin/no/nav/syfo/personstatus/application/PersonoversiktSearchService.kt, src/main/kotlin/no/nav/syfo/personstatus/application/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/PopulateNavnAndFodselsdatoCronjob.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/behandlendeenhet/PersonBehandlendeEnhetCronjob.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/ArbeidsuforhetvurderingConsumer.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/KafkaModule.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/manglendemedvirkning/ManglendeMedvirkningVurderingConsumer.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/meroppfolging/SenOppfolgingKandidatStatusConsumer.kt, src/test/kotlin/no/nav/syfo/aktivitetskravvurdering/kafka/AktivitetskravVurderingConsumerSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/application/PersonoversiktStatusServiceSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/ArbeidsuforhetvurderingConsumerSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/manglendemedvirkning/ManglendeMedvirkningVurderingConsumerSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/kafka/meroppfolging/SenOppfolgingKandidatStatusConsumerSpek.kt, src/test/kotlin/no/nav/syfo/testutil/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/TestApiModule.kt
- Flytter servicer som vi har i mappen `/personstatus` ned i `application` laget i `/personstatus` modulen.
=> IS: Refactor services into application folder

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/OppfolgingstilfelleConsumer.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/pdl/PdlClient.kt
- Legger til error handling i `hentPerson` kallet til pdl klienten.
- Legger også til info log på når man mottar records som vi har i andre consumers.
- Noe mer logging eller error handling vi bør legge til her?
=> IS: Add error handling to hentPerson pdl http request

src/main/kotlin/no/nav/syfo/personstatus/application/PersonoversiktStatusService.kt
Kanskje det bare er det at PDL ikke liker en tom liste med ident'er?
=> Avoid calling PDL with empty list

src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktSearchApiSpek.kt
Slo meg at søket på initialer kanskje kunne forenkles.
=> IS-2855: Forenkle søk med initialer

src/main/kotlin/no/nav/syfo/personstatus/api/v2/model/SearchQueryDTO.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/SearchQuery.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktSearchApiSpek.kt
Tillater at søkekriterium har initials == null
=> IS-2855: Søk bare med fodselsdato

src/main/kotlin/no/nav/syfo/personstatus/domain/SearchQuery.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktSearchApiSpek.kt
For søk tillate initialer == tom streng
=> IS-2855: Tillate tom streng initialer

src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/reaper/ReaperCronjob.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/reaper/ReaperQueries.kt, src/test/kotlin/no/nav/syfo/cronjob/reaper/ReaperCronjobSpek.kt
=> IS-2486: Nullstille veilederknytning etter 2 mnd

.nais/naiserator-dev.yaml
Se slacktråd: https://nav-it.slack.com/archives/C012X71FN04/p1733126209376329?thread_ts=1732620948.525049&cid=C012X71FN04
=> IS-2858: Add access for robot-api in dev

.nais/naiserator-prod.yaml
Se slack: https://nav-it.slack.com/archives/C012X71FN04/p1732620948525049
=> IS-2916: Add access for robot-api in prod

src/main/kotlin/no/nav/syfo/personstatus/application/aktivitetskrav/AktivitetskravDTO.kt
Lagt til vurderingsårsaker for aktivitetskravvurdering slik at det er mulig å vise de i syfooversikt
=> IS-3068: Lagt til vurderingsårsaker for aktivitetskravvurdering

src/main/kotlin/no/nav/syfo/personstatus/api/v2/endpoints/PersonTildelingApiV2.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PPersonOversiktStatus.kt, src/main/kotlin/no/nav/syfo/personstatus/domain/PersonOversiktStatus.kt
Logger warning med uuid når tilgangskontrollen gir rom respons.
=> IS-3094: Logge uuid når tilgangskontrollen gir tom respons

src/main/resources/db/migration/V18_08__close_motesvar.sql
Lukker utdatert møtesvaroppgave
=> IS-3208: Lukk utdatert motesvaroppgave

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/ApiModule.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/access/APIConsumerAccessService.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/access/ForbiddenAccessSystemConsumer.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/access/PreAuthorizedApplication.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/auth/ApiFeature.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/auth/JwtIssuer.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/auth/TokenAuth.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/endpoints/PersonTildelingSystemApi.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/azuread/AzureEnvironment.kt, src/test/kotlin/no/nav/syfo/personstatus/api/system/PersontildelingSystemApiSpek.kt, src/test/kotlin/no/nav/syfo/testutil/JWTUtils.kt, src/test/kotlin/no/nav/syfo/testutil/TestEnvironment.kt
Trenger et system-api her slik at en cronjob i `syfobehandlendeenhet` kan sjekke om en arbeidstaker har fått tildelt veileder.
=> IS-3255: System-api hente tildelt veileder

src/main/kotlin/no/nav/syfo/personstatus/application/PersonBehandlendeEnhetService.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/behandlendeenhet/BehandlendeEnhetClient.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/behandlendeenhet/BehandlendeEnhetResponseDTO.kt, src/test/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetCronjobSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/BehandlerdialogPersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/DialogmotekandidatPersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/application/PersonBehandlendeEnhetServiceSpek.kt, src/test/kotlin/no/nav/syfo/testutil/mock/SyfobehandlendeenhetMock.kt
Før vi kan refaktorere DTOen i `syfobehandlendeenhet` må vi endre dette her. Se også https://github.com/navikt/syfobehandlendeenhet/pull/192
=> IS-3263: Refactor DTO from syfobehandlendeenhet

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/cache/ValkeyStore.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/ApiModule.kt, src/main/kotlin/no/nav/syfo/personstatus/api/v2/endpoints/PersonTildelingApiV2.kt, src/main/kotlin/no/nav/syfo/personstatus/application/PersonBehandlendeEnhetService.kt, src/main/kotlin/no/nav/syfo/personstatus/application/PersonTildelingService.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/veileder/VeilederClient.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersontildelingApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/clients/veileder/VeilederClientSpek.kt, src/test/kotlin/no/nav/syfo/testutil/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/InternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testutil/TestApiModule.kt, src/test/kotlin/no/nav/syfo/testutil/mock/SyfoveilederMock.kt
Validerer at veileder som settes for en arbeidstaker er en aktiv veileder knyttet til oppfølgingsenheten for arbeidstakeren.
=> IS-3256: Veileder må tilhøre arbeidstakers oppfølgingsenhet

src/main/kotlin/no/nav/syfo/personstatus/application/PersonTildelingService.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersontildelingApiV2Spek.kt
Det er en god del tildelinger som feiler nå pga. av dette, så foreslår at vi utsetter innføring av denne valideringen til etter at vi har rullet ut vo-ruting til alle.
=> IS-3256: Vente med at veileder må tilhøre arbeidstakers oppfølgingsenhet

src/main/kotlin/no/nav/syfo/personstatus/application/PersonBehandlendeEnhetService.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/clients/behandlendeenhet/BehandlendeEnhetResponseDTO.kt, src/test/kotlin/no/nav/syfo/cronjob/behandlendeenhet/PersonBehandlendeEnhetCronjobSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/BehandlerdialogPersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/DialogmotekandidatPersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/api/v2/PersonoversiktStatusApiV2Spek.kt, src/test/kotlin/no/nav/syfo/personstatus/application/PersonBehandlendeEnhetServiceSpek.kt, src/test/kotlin/no/nav/syfo/personstatus/infrastructure/database/PersonOversiktStatusRepositorySpek.kt, src/test/kotlin/no/nav/syfo/testutil/UserConstants.kt, src/test/kotlin/no/nav/syfo/testutil/mock/SyfobehandlendeenhetMock.kt
Tilpasset ny struktur for behandlendeenhet-DTO
=> IS-3171: Tilpasset ny struktur for behandlendeenhet-DTO

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
- Legger til at appen `oppgave` til team aap kan kalle endepunkt hos oss
=> IS-3299: Add aap to inbound access

src/main/kotlin/no/nav/syfo/personstatus/application/IPersonOversiktStatusRepository.kt, src/main/kotlin/no/nav/syfo/personstatus/application/PersonoversiktStatusService.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/cronjob/reaper/ReaperCronjob.kt, src/main/kotlin/no/nav/syfo/personstatus/infrastructure/database/repository/PersonOversiktStatusRepository.kt, src/test/kotlin/no/nav/syfo/cronjob/reaper/ReaperCronjobSpek.kt
Det er en del sykmeldte som får oppgave på feil enhet når de blir syke på nytt. Nuller derfor enhet når oppfølgingen avsluttes.
=> IS-3304: Nulle enhet samtidig med veileder

src/main/kotlin/no/nav/syfo/personstatus/application/aktivitetskrav/AktivitetskravDTO.kt
- Legger til `beskrivelse` i respons slik at denne kan vises i `syfooversikt`
=> IS-3067: Add avvent beskrivelse to dto
